package resolvconf

import (
	"reflect"
	"strings"
	"testing"
)

func TestParse(t *testing.T) {
	c, err := parse(strings.NewReader(`
# Generated by resolvconf
search home
nameserver 9.9.9.10
nameserver 192.168.2.1
`))
	if err != nil {
		t.Fatal(err)
	}

	expCfg := Config{
		Nameservers:   []string{"9.9.9.10", "192.168.2.1"},
		SearchDomains: []string{"home"},
	}
	if !reflect.DeepEqual(c, expCfg) {
		t.Fatalf("Parse() = %v, expected %v", c, expCfg)
	}
}
